---
- name: Update Apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Checking essentials
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - curl
    - git-core
    - bash
    - openssl
    - libssl-dev
    - libssl-doc